// Generate dHybridR Fortran namelist input file from form state

function generateInputFile(state, dim) {
  const lines = [];
  const hr = '!------';

  lines.push('! ------------------------------------------------------------------------------');
  lines.push('!');
  lines.push('!   dHybridR input file — generated by dHybridR Input Generator');
  lines.push('!');
  lines.push(`!   ${dim}D simulation`);
  lines.push(`!   Generated: ${new Date().toISOString().slice(0,19).replace('T',' ')}`);
  lines.push('!');
  lines.push('! ------------------------------------------------------------------------------');
  lines.push('');

  // Output order matches ReadInputFile call order
  const globalSections = [
    'node_conf', 'time', 'grid_space', 'global_output', 'restart',
    'ext_emf', 'ext_force', 'field_diag', 'algorithm', 'loadbalance', 'particles',
  ];
  const perSpeciesSections = [
    'species', 'boundary_conditions', 'plasma_injector',
    'diag_species', 'raw_diag', 'track_diag',
  ];

  for (const skey of globalSections) {
    const sec = SCHEMA[skey];
    const data = state[skey];
    if (!sec || !data) continue;
    if (sec.enabled === false && !data._enabled) continue;
    lines.push(...formatSection(sec, skey, data, dim));
    lines.push('');
  }

  const numSpecies = state.particles?.num_species || 1;
  for (let sp = 0; sp < numSpecies; sp++) {
    lines.push(`!----------information for species ${sp+1}` + '-'.repeat(40));
    for (const skey of perSpeciesSections) {
      const sec = SCHEMA[skey];
      const dataArr = state[skey];
      if (!sec || !dataArr) continue;

      if (sec.multiPerSpecies) {
        // Multiple blocks per species (e.g. injectors)
        const injectors = dataArr[sp] || [];
        for (let inj = 0; inj < injectors.length; inj++) {
          const data = injectors[inj] || {};
          if (sec.enabled === false && !data._enabled) continue;
          lines.push(...formatSection(sec, skey, data, dim, sp+1, inj+1));
          lines.push('');
        }
      } else {
        const data = dataArr[sp] || {};
        if (sec.enabled === false && !data._enabled) continue;
        lines.push(...formatSection(sec, skey, data, dim, sp+1));
        lines.push('');
      }
    }
  }

  return lines.join('\n');
}

function formatSection(sec, skey, data, dim, speciesNum, injectorNum) {
  const lines = [];
  // Section name mapping: namelist nl_X reads input section X
  const sectionName = sec.namelist.replace('nl_', '');
  let comment = sec.label;
  if (speciesNum) comment += ` (Species ${speciesNum}`;
  if (injectorNum) comment += `, #${injectorNum}`;
  if (speciesNum) comment += ')';
  lines.push(`!${'-'.repeat(10)} ${comment} ${'-'.repeat(Math.max(2, 60 - comment.length))}`);
  lines.push(sectionName);
  lines.push('{');

  for (const field of sec.fields) {
    if (field.advanced && isDefaultValue(field, data[field.key], dim)) continue;
    const val = data[field.key];
    if (val === undefined || val === null) continue;
    const formatted = formatValue(field, val, dim);
    if (formatted === null) continue;

    const hint = field.hint ? `  ! ${field.hint}` : '';
    lines.push(`\t${formatted},${hint}`);
  }

  lines.push('}');
  return lines;
}

function formatValue(field, val, dim) {
  const arrSize = getArraySize(field.dim, dim);

  if (arrSize > 0) {
    // Array value
    let arr = Array.isArray(val) ? val.slice(0, arrSize) : [val];
    while (arr.length < arrSize) arr.push(field.default?.[arr.length] ?? 0);

    if (field.type === 'strarr') {
      // For fparser arrays (e.g. vsp): if any component is non-empty, fill empty ones with "0."
      // Fortran requires all components set for the function to activate
      if (field.fparser && arr.some(v => String(v).trim() !== '')) {
        arr = arr.map(v => String(v).trim() === '' ? '0.' : v);
      }
      const parts = arr.map(v => {
        let sv = String(v);
        if (field.fparser) sv = sv.replace(/\bpi\b/gi, '3.14159265358979');
        return `"${sv}"`;
      });
      return `${field.key}=${parts.join(',')}`;
    } else if (field.type === 'bool') {
      const parts = arr.map(v => v ? '.true.' : '.false.');
      return `${field.key}(1:${arrSize})= ${parts.join(', ')}`;
    } else {
      const parts = arr.map(v => formatNumber(v, field.type));
      return `${field.key}(1:${arrSize})=${parts.join(',')}`;
    }
  }

  // Special: phasespaces is stored as comma-separated but output as individual quoted strings
  if (field.key === 'phasespaces' && field.type === 'str') {
    const items = String(val).split(',').map(s => s.trim()).filter(s => s);
    if (items.length === 0) return null;
    const parts = items.map(s => `"${s}"`);
    return `${field.key}=${parts.join(',')}`;
  }

  // Scalar
  if (field.type === 'bool') {
    return `${field.key}=${val ? '.true.' : '.false.'}`;
  } else if (field.type === 'str') {
    let sval = String(val);
    // Replace pi with numeric value for Fortran fparser compatibility
    if (field.fparser) sval = sval.replace(/\bpi\b/gi, '3.14159265358979');
    if (needsQuotes(field)) {
      return `${field.key}="${sval}"`;
    }
    return `${field.key}="${sval}"`;
  } else {
    return `${field.key}=${formatNumber(val, field.type)}`;
  }
}

function formatNumber(v, type) {
  if (type === 'int') return String(Math.round(Number(v)));
  let n = Number(v);
  if (!isFinite(n)) return '0.';
  // Use scientific notation for very large/small
  let s = String(n);
  if (s.includes('e') || s.includes('E')) {
    return s.replace('e','d').replace('E','d');
  }
  // Ensure there's a decimal point for reals
  if (type === 'real' && !s.includes('.')) s += '.';
  return s;
}

function needsQuotes(field) {
  // All string fields in Fortran namelists need quotes
  return true;
}

function getArraySize(dimSpec, dim) {
  if (dimSpec === 0) return 0;
  if (dimSpec === 'DIM') return dim;
  if (dimSpec === 'DIM2') return dim * 2;
  if (dimSpec === 'BDIM') return (dim - 1) * 2;
  if (dimSpec === 'VDIM') return 3;
  if (dimSpec === 'VDIM_STR') return 3;
  if (typeof dimSpec === 'number') return dimSpec;
  return 0;
}

function isDefaultValue(field, val, dim) {
  if (val === undefined || val === null) return true;
  const arrSize = getArraySize(field.dim, dim);
  if (arrSize > 0) {
    if (!Array.isArray(val)) return false;
    const def = field.default || [];
    for (let i = 0; i < arrSize; i++) {
      if (String(val[i]) !== String(def[i])) return false;
    }
    return true;
  }
  return String(val) === String(field.default);
}
